### ISSUE TITLE
I'm getting this error

### ISSUE THREAD

**Issue by RehanPlayz** [AlphaNecron/Chakram#10]
```
Invalid `prisma.user.findFirst()` invocation:


  User `pterodactyl` was denied access on the database `pterodactyl.public`
    at cb (/workspace/Testing-Stuff/Void/node_modules/@prisma/client/runtime/index.js:38741:17)
    at async handler (/workspace/Testing-Stuff/Void/.next/server/pages/api/auth/login.js:30:16)
    at async Object.apiResolver (/workspace/Testing-Stuff/Void/node_modules/next/dist/server/api-utils.js:101:9)
    at async Server.handleApiRequest (/workspace/Testing-Stuff/Void/node_modules/next/dist/server/next-server.js:770:9)
```

**Comment by RehanPlayz** [comment]
DB Log
```
2021-10-10 06:36:11.216 UTC [23] FATAL:  no pg_hba.conf entry for host "150.136.146.208", user "pterodactyl", database "pterodactyl", SSL off
2021-10-11 09:19:47.321 UTC [24] FATAL:  no pg_hba.conf entry for host "13.233.190.188", user "pterodactyl", database "pterodactyl", SSL off
2021-10-11 09:22:47.988 UTC [25] FATAL:  no pg_hba.conf entry for host "13.233.190.188", user "pterodactyl", database "pterodactyl", SSL off
```

**Comment by RehanPlayz** [comment]
@AlphaNecron

**Comment by AlphaNecron** [comment]
It's probably conflicting with Pterodactyl, try disabling Pterodactyl and see.

**Comment by RehanPlayz** [comment]
> It's probably conflicting with Pterodactyl, try disabling Pterodactyl and see.

Ummm what?, The DB is hosted using Ptero and the name of the DB is pterodactyl. I asked someone and they said I have to add the IP config file but idk how

**Comment by AlphaNecron** [comment]
Recheck the database url, username and password.

**Comment by RehanPlayz** [comment]
> Recheck the database url, username and password.

I did.... I can even send you the creds if you want to double check

**Comment by AlphaNecron** [comment]
Is your port blocked? Try connecting to it via your PC.

**Comment by AlphaNecron** [comment]
Closed due to inactivity.
