### ISSUE TITLE
unable to upload file , "Unexpected token I in JSON at position 0"

### ISSUE THREAD

**Issue by changchichung** [AlphaNecron/Chakram#18]
after succeful login to Void with admin , I can not upload anyfile due to the error "Unexpected token I in JSON at position 0"
docker logs show 
```
 12:47:25 PM  INFO/FILE  User admin (1) uploaded a file: iMx6Sb.wzr-hp-ag300n_tftp方式_WAN (4)
TypeError: Cannot read property 'logFile' of undefined
    at handler (/void/.next/server/pages/api/upload.js:94:17)
    at async Object.apiResolver (/void/node_modules/next/dist/server/api-utils.js:101:9)
    at async Server.handleApiRequest (/void/node_modules/next/dist/server/next-server.js:770:9)
    at async Object.fn (/void/node_modules/next/server/next-server.ts:975:24)
    at async Router.execute (/void/node_modules/next/server/router.ts:346:21)
    at async Server.run (/void/node_modules/next/server/next-server.ts:1229:20)
    at async Server.handleRequest (/void/node_modules/next/dist/server/next-server.js:292:20)
```
and in browser , there's something like 
![](https://i.imgur.com/mJMrBMQ.png)

but the file did upload.
```
chchang@cch-acer:~/git/Void$ ls -lart uploads/
總用量 36
-rwxrwxrwx  1 root    root    2894 Nov 10 20:46 419G5S.py
-rwxrwxrwx  1 root    root    2031 Nov 10 20:46 lyf4iw.wzr-hp-ag300n_tftp
-rw-r--r--  1 root    root    2031 Nov 10 20:47 mARA9E.wzr-hp-ag300n_tftp
-rw-r--r--  1 root    root    2031 Nov 10 20:47 iMx6Sb.wzr-hp-ag300n_tftp方式_WAN
-rw-r--r--  1 root    root    2031 Nov 10 20:47 jFn1wJ.wzr-hp-ag300n_tftp方式_WAN
-rw-r--r--  1 root    root    2031 Nov 10 20:49 nYsGHz.wzr-hp-ag300n_tftp方式_WAN
drwxrwxrwx  2 root    root    4096 Nov 10 20:50 .
chchang@cch-acer:~/git/Void$ 
```
and I can see the files in files/list
![](https://i.imgur.com/MeAFIZK.png)
but show none in grid
![](https://i.imgur.com/lItnWDM.png)

**Comment by AlphaNecron** [comment]
Ok will push a fix asap.

**Comment by AlphaNecron** [comment]
Btw grid is intended to show images and videos only.

**Comment by AlphaNecron** [comment]
Pull the latest `dev` image and see if the issue has been fixed.
