### ISSUE TITLE
Build command is breaking

### ISSUE THREAD

**Issue by itsyashvardhan** [AlphaNecron/Chakram#29]
Error displayed in console on running `npm run build` or `yarn build` 
```bash
> void@0.5.1 build:next
> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
info  - Creating an optimized production build ...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/container/Void/node_modules/next/dist/compiled/webpack/bundle5.js:138971:18)
    at BulkUpdateDecorator.update (/home/container/Void/node_modules/next/dist/compiled/webpack/bundle5.js:138872:50)
    at /home/container/Void/node_modules/next/dist/compiled/webpack/bundle5.js:59321:9
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
ERROR: "build:next" exited with 1.
```

**Comment by AlphaNecron** [comment]
Use `node<=16`.

**Comment by AlphaNecron** [comment]
Feel free to reopen the issue if the problem still persists.
