### ISSUE TITLE
Couple build issues

### ISSUE THREAD

**Issue by DoctorDinosaur** [AlphaNecron/Chakram#31]
1. `Error: Expected linebreaks to be 'LF' but found 'CRLF'.  linebreak-style` (I have to change the linebreak style manually in .eslintrc.js
2. `./src/pages/_document.tsx
2:1  Error: next/document should not be imported outside of pages/_document.js. See https://nextjs.org/docs/messages/no-document-import-in-page.  @next/next/no-document-import-in-page` (Fixed by updating next/es-config-next to latest, 11.1.3)
3. I don't know how to solve this one
```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:18:327)
    at exports.useMemo (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:23:109)
    at useStore (E:\Downloads\New folder\void\.next\server\chunks\271.js:103:37)
    at Void (E:\Downloads\New folder\void\.next\server\pages\_app.js:43:84)
    at d (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (E:\Downloads\New folder\Void\node_modules\next\dist\server\render.js:596:45)

Error occurred prerendering page "/auth/login". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:18:327)
    at exports.useMemo (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:23:109)
    at useStore (E:\Downloads\New folder\void\.next\server\chunks\271.js:103:37)
    at Void (E:\Downloads\New folder\void\.next\server\pages\_app.js:43:84)
    at d (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (E:\Downloads\New folder\Void\node_modules\next\dist\server\render.js:596:45)

Error occurred prerendering page "/dash". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:18:327)
    at exports.useMemo (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:23:109)
    at useStore (E:\Downloads\New folder\void\.next\server\chunks\271.js:103:37)
    at Void (E:\Downloads\New folder\void\.next\server\pages\_app.js:43:84)
    at d (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (E:\Downloads\New folder\Void\node_modules\next\dist\server\render.js:596:45)

Error occurred prerendering page "/dash/users". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:18:327)
    at exports.useMemo (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:23:109)
    at useStore (E:\Downloads\New folder\void\.next\server\chunks\271.js:103:37)
    at Void (E:\Downloads\New folder\void\.next\server\pages\_app.js:43:84)
    at d (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (E:\Downloads\New folder\Void\node_modules\next\dist\server\render.js:596:45)

Error occurred prerendering page "/dash/urls". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:18:327)
    at exports.useMemo (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:23:109)
    at useStore (E:\Downloads\New folder\void\.next\server\chunks\271.js:103:37)
    at Void (E:\Downloads\New folder\void\.next\server\pages\_app.js:43:84)
    at d (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (E:\Downloads\New folder\Void\node_modules\next\dist\server\render.js:596:45)

Error occurred prerendering page "/dash/upload". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:18:327)
    at exports.useMemo (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:23:109)
    at useStore (E:\Downloads\New folder\void\.next\server\chunks\271.js:103:37)
    at Void (E:\Downloads\New folder\void\.next\server\pages\_app.js:43:84)
    at d (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (E:\Downloads\New folder\Void\node_modules\next\dist\server\render.js:596:45)
[ ===] info  - Generating static pages (6/7)
Error occurred prerendering page "/dash/files". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at S (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:18:327)
    at exports.useMemo (E:\Downloads\New folder\void\node_modules\react\cjs\react.production.min.js:23:109)
    at useStore (E:\Downloads\New folder\void\.next\server\chunks\271.js:103:37)
    at Void (E:\Downloads\New folder\void\.next\server\pages\_app.js:43:84)
    at d (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (E:\Downloads\New folder\Void\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (E:\Downloads\New folder\Void\node_modules\next\dist\server\render.js:596:45)
info  - Generating static pages (7/7)

> Build error occurred
Error: Export encountered errors on following paths:
        /
        /auth/login
        /dash
        /dash/files
        /dash/upload
        /dash/urls
        /dash/users
    at E:\Downloads\New folder\Void\node_modules\next\dist\export\index.js:487:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (E:\Downloads\New folder\Void\node_modules\next\dist\telemetry\trace\trace.js:60:20)
    at async E:\Downloads\New folder\Void\node_modules\next\dist\build\index.js:833:17
    at async Span.traceAsyncFn (E:\Downloads\New folder\Void\node_modules\next\dist\telemetry\trace\trace.js:60:20)
    at async E:\Downloads\New folder\Void\node_modules\next\dist\build\index.js:707:13
    at async Span.traceAsyncFn (E:\Downloads\New folder\Void\node_modules\next\dist\telemetry\trace\trace.js:60:20)
    at async Object.build [as default] (E:\Downloads\New folder\Void\node_modules\next\dist\build\index.js:77:25)
ERROR: "build:next" exited with 1.
```

**Comment by AlphaNecron** [comment]
Uhh are you using React 18?

**Comment by DoctorDinosaur** [comment]
React 17

That's what was/is in your package.json

**Comment by AlphaNecron** [comment]
Please use Linux instead, I haven't tested Void on Windoze...

**Comment by DoctorDinosaur** [comment]
Ah damn :(

I'm trying to pre-build before I upload to my linux vps; since I wanna run it in a ptero egg where I don't have a terminal

**Comment by AlphaNecron** [comment]
Use the Docker image then.

**Comment by DoctorDinosaur** [comment]
Builds successfully with Ubuntu via Windows WSL 2

Shame I can't just build with my local install of node, not sure whats going on with the package versions etc

**Comment by AlphaNecron** [comment]
You need `node<=16` btw.

**Comment by DoctorDinosaur** [comment]
![image](https://user-images.githubusercontent.com/26852749/173226317-0edc93e1-3cab-4206-8ab2-8f9b47a2734c.png)
Yeah, that's what I have

It just builds on WSL Ubuntu (i.e. linux) and not windows. Not sure why.

**Comment by AlphaNecron** [comment]
Most of the dependencies are built with Linux, thus they are compatible with Linux. If you want to use Windows, you might need to rebuild all of them with `npm rebuild --build-from source` (not sure whether it works btw).
