### ISSUE TITLE
Database_URL on Yarn Build

### ISSUE THREAD

**Issue by MayhemBill** [AlphaNecron/Chakram#35]
```
[    ] info  - Generating static pages (0/7)(node:20666) UnhandledPromiseRejectionWarning: Error: error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
   |
 2 |   provider = "postgresql"
 3 |   url      = env("DATABASE_URL")
   |

Validation Error Count: 1
    at Object.loadEngine (/home/pi/6tbdata/Void/node_modules/@prisma/client/runtime/index.js:35582:19)
    at async Object.instantiateLibrary (/home/pi/6tbdata/Void/node_modules/@prisma/client/runtime/index.js:35511:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20666) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20666) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info  - Generating static pages (7/7)
info  - Finalizing page optimization
```
In the config.toml the database url is set, but I get this when running yarn build, using node 14.19.3 and yarn 1.22.18

**Comment by AlphaNecron** [comment]
Just ignore it, that does not matter. It's a bug which will be fixed in `v1`.

**Comment by MayhemBill** [comment]
it does matter as I cannot login because of it
when I try to login I get this error:

```
PrismaClientInitializationError:
Invalid `prisma.user.findFirst()` invocation:


  Database `voiduploader.public` does not exist on the database server at `localhost:5432`.
    at Object.request (/home/pi/6tbdata/Void/node_modules/@prisma/client/runtime/index.js:39815:15)
    at async PrismaClient._request (/home/pi/6tbdata/Void/node_modules/@prisma/client/runtime/index.js:40637:18)
    at async handler (/home/pi/6tbdata/Void/.next/server/pages/api/auth/login.js:30:16)
    at async Object.apiResolver (/home/pi/6tbdata/Void/node_modules/next/dist/server/api-utils.js:101:9)
    at async Server.handleApiRequest (/home/pi/6tbdata/Void/node_modules/next/dist/server/next-server.js:775:9)
    at async Object.fn (/home/pi/6tbdata/Void/node_modules/next/server/next-server.ts:985:24)
    at async Router.execute (/home/pi/6tbdata/Void/node_modules/next/server/router.ts:346:21)
    at async Server.run (/home/pi/6tbdata/Void/node_modules/next/server/next-server.ts:1239:20)
    at async Server.handleRequest (/home/pi/6tbdata/Void/node_modules/next/dist/server/next-server.js:292:20) {
  clientVersion: '3.10.0',
  errorCode: undefined
}
```

**Comment by AlphaNecron** [comment]
Try `prisma migrate deploy` and then `prisma db seed`. Use `npx` or `yarn`, depending on your PM.

**Comment by AlphaNecron** [comment]
Closed due to inactivity. Feel free to reopen if you encounter other issues.
