### ISSUE TITLE
Reverse proxy breaks file links

### ISSUE THREAD

**Issue by wtquin** [AlphaNecron/Chakram#36]
Using NPM as reverse proxy so that `https://void.domain.com` will end up at `<ip>:3000`. Using `docker-compose`.

When using `<ip>:3000` I can access Void and any direct links to files like `<ip>:3000/GX5ccH`. When switching to `https://void.domain.com`, all seems well and I can access the home page. However, when I now upload a file and try to visit _it's_ direct link, I end up with `500 Internal Server Error`. 

Using Portainer's log feature, these are the logs:
```
 10:22:54 PM  INFO/ROUTER  200 /api/upload
 10:22:54 PM  INFO/FILE  User quinten (1) uploaded a file: KnOD8s.jpg (2)
 10:23:00 PM  INFO/ROUTER  200 /KnOD8s
FetchError: request to http://void.quinten0508.com/r/KnOD8s.jpg failed, reason: getaddrinfo ENOTFOUND void.quinten0508.com
    at ClientRequest.<anonymous> (/void/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:475:12)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND'
} 
```
This log includes a file upload, which does work.

**Comment by AlphaNecron** [comment]
Try enabling `secure` in the config file?
